export interface BookingFormValues {
  customerId: string;
  slotId: string;
  checkInDate: Date;
  checkOutDate: Date;
  specialRequirements: string;
}

export interface BookingData {
  id?: number;
  customer_id: number;
  slot_id: number;
  check_in_date: string;
  check_out_date: string;
  special_requirements: string | null;
  status: 'pending' | 'confirmed' | 'cancelled';
  reservation_code?: string;
  created_at?: string;
}

// Type specifically for creating a new booking - reservation_code is generated by DB trigger
export type BookingInsertData = Omit<BookingData, 'id' | 'created_at' | 'reservation_code'>;

// Add a type assertion function to help TypeScript understand the insert operation
export function assertBookingInsert(booking: BookingInsertData): BookingInsertData {
  return booking;
}