export interface BookingFormValues {
  customerId: string;
  slotId: string;
  checkInDate: Date;
  checkOutDate: Date;
  specialRequirements: string;
}

// Type for data coming from the database
export interface BookingData {
  customer_id: number;
  slot_id: number;
  check_in_date: string;
  check_out_date: string;
  special_requirements: string | null;
  status: 'pending' | 'confirmed' | 'cancelled';
  reservation_code?: string; // Made optional since it's generated by trigger
}

// Type specifically for creating a new booking
export interface CreateBookingData extends Omit<BookingData, 'reservation_code'> {
  customer_id: number;
  slot_id: number;
  check_in_date: string;
  check_out_date: string;
  special_requirements: string | null;
  status: 'pending';
}