export interface BookingFormValues {
  customerId: string;
  slotId: string;
  checkInDate: Date;
  checkOutDate: Date;
  specialRequirements: string;
}

// Type that matches exactly what's in the database
export interface BookingData {
  id?: number;
  customer_id: number;
  slot_id: number;
  check_in_date: string;
  check_out_date: string;
  special_requirements: string | null;
  status: 'pending' | 'confirmed' | 'cancelled';
  reservation_code?: string; // Optional because it's generated by DB trigger
  created_at?: string;
}

// Type for inserting a new booking - excludes auto-generated fields
export type BookingInsertData = {
  customer_id: number;
  slot_id: number;
  check_in_date: string;
  check_out_date: string;
  special_requirements?: string | null;
  status: 'pending' | 'confirmed' | 'cancelled';
};