export type Slot = {
  id: number;
  name: string;
  status: "available" | "occupied" | "maintenance";
  customer_id?: number;
  maintenance_id?: number;
  location_coordinates?: any;
  created_at?: string;
  updated_at?: string;
  dock?: string;
  length_ft?: number;
  width_ft?: number;
  is_covered?: boolean;
  electricity_voltage?: string;
  has_water?: boolean;
  zone?: string;
  location_identifier: string;
  last_activity_at?: string;
  utility_connection_type?: string;
  user_id?: string;
  site_type?: string;
  hookup_type?: string;
  surface_type?: string;
  amenities?: any;
  max_capacity?: any;
  special_features?: any;
  pricing?: any;
  photos?: string[];
  notes?: string;
  distance_to_facilities?: any;
  assets?: any[];
};