export type MarinaDetails = {
  id: number;
  name: string;
  address?: string | null;
  contact_email?: string | null;
  contact_phone?: string | null;
  total_slips?: number | null;
  created_at?: string | null;
  updated_at?: string | null;
  website?: string | null;
  coordinates?: any | null;
  approach_info?: any | null;
  services_amenities?: any | null;
  other_features?: any | null;
  social_media?: any | null;
  photos?: string[] | null;
  videos?: string[] | null;
  user_id?: string | null;
};

export type Slot = {
  id: number;
  name: string;
  status: string;
  customer_id?: number | null;
  maintenance_id?: number | null;
  location_coordinates?: any | null;
  created_at?: string | null;
  updated_at?: string | null;
  dock?: string | null;
  length_ft?: number | null;
  width_ft?: number | null;
  is_covered?: boolean | null;
  electricity_voltage?: string | null;
  has_water?: boolean | null;
  zone?: string | null;
  location_identifier: string;
  last_activity_at?: string | null;
  utility_connection_type?: string | null;
  user_id?: string | null;
};