// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhwbzinxpgtiwqhrrcvb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpod2J6aW54cGd0aXdxaHJyY3ZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzczNDE3MzgsImV4cCI6MjA1MjkxNzczOH0.SU4iUqgidnjpMv2XrN2CHQGnYrisJYppHxi98fwjJF4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);